export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_BOOKS_PENDING = 'REQUEST_BOOKS_PENDING';
export const REQUEST_BOOKS_SUCCESS = 'REQUEST_BOOKS_SUCCESS';
export const REQUEST_BOOKS_FAILED = 'REQUEST_BOOKS_FAILED';

export const ADD_BOOK = 'ADD_BOOK';
export const REMOVE_BOOK = 'REMOVE_BOOK';
